# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Dropbox\dragonfly\base\nautilus\view\main-window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hSplitter = QtWidgets.QSplitter(self.centralwidget)
        self.hSplitter.setOrientation(QtCore.Qt.Vertical)
        self.hSplitter.setObjectName("hSplitter")
        self.vSplitter = QtWidgets.QSplitter(self.hSplitter)
        self.vSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.vSplitter.setObjectName("vSplitter")
        self.tabWidget = QtWidgets.QTabWidget(self.vSplitter)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.nounsTab = QtWidgets.QWidget()
        self.nounsTab.setObjectName("nounsTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.nounsTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.nounsTree = QtWidgets.QTreeView(self.nounsTab)
        self.nounsTree.setHeaderHidden(True)
        self.nounsTree.setObjectName("nounsTree")
        self.verticalLayout_2.addWidget(self.nounsTree)
        self.tabWidget.addTab(self.nounsTab, "")
        self.verbsTab = QtWidgets.QWidget()
        self.verbsTab.setObjectName("verbsTab")
        self.tabWidget.addTab(self.verbsTab, "")
        self.exitsTab = QtWidgets.QWidget()
        self.exitsTab.setObjectName("exitsTab")
        self.tabWidget.addTab(self.exitsTab, "")
        self.widget = QtWidgets.QWidget(self.vSplitter)
        self.widget.setObjectName("widget")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.hSplitter)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.hSplitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_New = QtWidgets.QMenu(self.menu_File)
        self.menu_New.setObjectName("menu_New")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNewProject = QtWidgets.QAction(MainWindow)
        self.actionNewProject.setObjectName("actionNewProject")
        self.actionCloseProject = QtWidgets.QAction(MainWindow)
        self.actionCloseProject.setObjectName("actionCloseProject")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionOpenProject = QtWidgets.QAction(MainWindow)
        self.actionOpenProject.setObjectName("actionOpenProject")
        self.menu_New.addAction(self.actionNewProject)
        self.menu_File.addAction(self.menu_New.menuAction())
        self.menu_File.addAction(self.actionOpenProject)
        self.menu_File.addAction(self.actionCloseProject)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionExit)
        self.menubar.addAction(self.menu_File.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.actionExit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Nautilus"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.nounsTab), _translate("MainWindow", "Nouns"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.verbsTab), _translate("MainWindow", "Verbs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.exitsTab), _translate("MainWindow", "Exits"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_New.setTitle(_translate("MainWindow", "&New"))
        self.actionNewProject.setText(_translate("MainWindow", "&Project"))
        self.actionCloseProject.setText(_translate("MainWindow", "&Close Project"))
        self.actionExit.setText(_translate("MainWindow", "&Exit"))
        self.actionOpenProject.setText(_translate("MainWindow", "&Open Project"))
